Set H  hot process streams
/
1*15
/ ;

Set C  cold process streams
/
1*15
/ ;

Parameter FCpH(H)  F*Cp for hot process streams
/
1            1.10
2            2.00
3            1.50
4            2.50
5            1.80
6            0.80
7            1.30
8            1.70
9            1.20
10           1.30
11           2.30
12           2.30
13           1.30
14           1.60
15           2.00
/ ;

Parameter FCpC(C)  F*Cp for cold process streams
/
1            1.60
2            1.30
3            2.40
4            3.00
5            1.80
6            0.80
7            1.80
8            1.70
9            0.90
10           1.90
11           1.70
12           1.20
13           1.60
14           1.50
15           2.10
/ ;

